// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FancyboxController from "./fancybox_controller"
application.register("fancybox", FancyboxController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageController from "./image_controller"
application.register("image", ImageController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SelectallController from "./selectall_controller"
application.register("selectall", SelectallController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
