log_files:
  cron: "00 23 * * *" #at 23-00
  class: "CreateLogFilesScheduler"
  queue: "default"
delete_unattached_blobs_every_day:
  cron: "15 23 * * *" #at 23-15
  class: "DeleteUnattachedBlobsScheduler"
  queue: "default"